// <auto-generated />
namespace PostOfiice.DAta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Export_By_Service_Group_And_Time_District_Po_User_PPTT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Export_By_Service_Group_And_Time_District_Po_User_PPTT));
        
        string IMigrationMetadata.Id
        {
            get { return "201709040323344_Export_By_Service_Group_And_Time_District_Po_User_PPTT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
