// <auto-generated />
namespace PostOfiice.DAta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Export_service_group_time_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Export_service_group_time_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201708300344563_Export_service_group_time_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
