// <auto-generated />
namespace PostOfiice.DAta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class exporttcbcbytimedistrictpo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exporttcbcbytimedistrictpo));
        
        string IMigrationMetadata.Id
        {
            get { return "201711051514108_export-tcbc-by-time-district-po"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
