// <auto-generated />
namespace PostOfiice.DAta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class group_by_service_district_time_bccp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(group_by_service_district_time_bccp));
        
        string IMigrationMetadata.Id
        {
            get { return "201709010318466_group_by_service_district_time_bccp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
