// <auto-generated />
namespace PostOfiice.DAta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExportByServiceGroup_Time_Manager : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExportByServiceGroup_Time_Manager));
        
        string IMigrationMetadata.Id
        {
            get { return "201708300340184_Export By Service Group_Time_Manager"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
