// <auto-generated />
namespace PostOfiice.DAta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changetkbdhistoryv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetkbdhistoryv1));
        
        string IMigrationMetadata.Id
        {
            get { return "201710190851501_change-tkbd-history-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
