// <auto-generated />
namespace PostOfiice.DAta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addperiodsavingtypeinteresttypeinterestratetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addperiodsavingtypeinteresttypeinterestratetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201710171504501_add-period-savingtype-interesttype-interestrate-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
